AWSTemplateFormatVersion: "2010-09-09"

Mappings:
  Images:
    us-east-1:
      ubuntu: "ami-03ededff12e34e59e"


Parameters:
  OsName:
    Type: String
    Default: "ubuntu"

Outputs:
  IdImagen:
    Description: cosas
    Value: !FindInMap [Images, !Ref "AWS::Region", !Ref OsName ]

Resources:

  SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group que permite acceso ssh"
      VpcId: "vpc-04e74c746436e103a"
        
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0         
  