AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Este stack va a crear
  una instancia y todo lo
  que necesita

Mappings:
  Images:
    us-east-1:
      amazonlinux: "ami-03ededff12e34e59e"
      ubuntu: "ami-04505e74c0741db8d"
      debian: "ami-07d02ee1eeb0c996c"


Parameters:
  OsName:
    Type: String
  VpcIdParameter:
    Type: String
  KeyPairParameter:
    Type: String
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t3.micro
      - t3.small    
      - t2.micro
    Description: El tipo de instancia a crear

Outputs:
  PublicIp:
    Description: IP Publica de la instancia
    Value: !GetAtt WebServer.PublicIp
  IdImagen:
    Description: id de la imagen
    Value: !FindInMap [Images, !Ref "AWS::Region", !Ref OsName ]
  IdInstancia:
    Description: Id De la instancia que hemos creado
    Value: !Ref WebServer       

Resources:
  SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group que permite acceso ssh"
      VpcId: 
        Ref: VpcIdParameter
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0         
  WebServer:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: !FindInMap [Images, !Ref "AWS::Region", !Ref OsName ]
      KeyName: 
        Ref: KeyPairParameter
      InstanceType: 
        Ref: InstanceTypeParameter
      SecurityGroupIds: 
        - Ref: SecurityGroupSSH