AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Este stack va a crear
  una instancia y todo lo
  que necesita
Resources:
  WebServer:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: "ami-03ededff12e34e59e"
